{
  "comments": [
    {
      "key": {
        "uuid": "ad21b210_7936865e",
        "filename": "fixtures/vm_test.py",
        "patchSetId": 1
      },
      "lineNbr": 2907,
      "author": {
        "id": 128
      },
      "writtenOn": "2020-02-05T08:40:19Z",
      "side": 1,
      "message": "consider using @retry",
      "revId": "8af88fd6cf9e382f43a187a88720d386fa2923d4",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "cddcf536_c83c9bd0",
        "filename": "scripts/policy/test_policy.py",
        "patchSetId": 1
      },
      "lineNbr": 166,
      "author": {
        "id": 128
      },
      "writtenOn": "2020-02-05T08:40:19Z",
      "side": 1,
      "message": "Is this call to sleep() required? In line 177, inside the loop sleep() is invoked after run_cmd_on_vm()",
      "revId": "8af88fd6cf9e382f43a187a88720d386fa2923d4",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}